const rows = [
  {
    id: 1,
    title_en: `I like to work on cars`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 1,
    sort_idx: 1,
    active: 1,
  },
  {
    id: 2,
    title_en: `I like to do puzzles`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 1,
    sort_idx: 2,
    active: 1,
  },
  {
    id: 3,
    title_en: `I am good at working independently`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 1,
    sort_idx: 3,
    active: 1,
  },
  {
    id: 4,
    title_en: `I like to work in teams`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 1,
    sort_idx: 4,
    active: 1,
  },
  {
    id: 5,
    title_en: `I am an ambitious person, I set goals for myself`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 1,
    sort_idx: 5,
    active: 1,
  },
  {
    id: 6,
    title_en: `I like to organize things, (files, desks/offices)`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 1,
    sort_idx: 6,
    active: 1,
  },
  {
    id: 7,
    title_en: `I like to build things`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 1,
    sort_idx: 7,
    active: 1,
  },
  {
    id: 8,
    title_en: `I like to read about art and music`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 2,
    sort_idx: 8,
    active: 1,
  },
  {
    id: 9,
    title_en: `I like to have clear instructions to follow`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 2,
    sort_idx: 9,
    active: 1,
  },
  {
    id: 10,
    title_en: `I like to try to influence or persuade people`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 2,
    sort_idx: 10,
    active: 1,
  },
  {
    id: 11,
    title_en: `I like to do experiments`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 2,
    sort_idx: 11,
    active: 1,
  },
  {
    id: 12,
    title_en: `I like to teach or train people`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 2,
    sort_idx: 12,
    active: 1,
  },
  {
    id: 13,
    title_en: `I like trying to help people solve their problems`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 2,
    sort_idx: 13,
    active: 1,
  },
  {
    id: 14,
    title_en: `I like to take care of animals`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 2,
    sort_idx: 14,
    active: 1,
  },
  {
    id: 15,
    title_en: `I wouldn't mind working 8 hours per day in an office`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 3,
    sort_idx: 15,
    active: 1,
  },
  {
    id: 16,
    title_en: `I like selling things`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 3,
    sort_idx: 16,
    active: 1,
  },
  {
    id: 17,
    title_en: `I enjoy creative writing`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 3,
    sort_idx: 17,
    active: 1,
  },
  {
    id: 18,
    title_en: `I enjoy science`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 3,
    sort_idx: 18,
    active: 1,
  },
  {
    id: 19,
    title_en: `I am quick to take on new responsibilities`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 3,
    sort_idx: 19,
    active: 1,
  },
  {
    id: 20,
    title_en: `I am interested in healing people`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 3,
    sort_idx: 20,
    active: 1,
  },
  {
    id: 21,
    title_en: `I enjoy trying to figure out how things work`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 3,
    sort_idx: 21,
    active: 1,
  },
  {
    id: 22,
    title_en: `I like putting things together or assembling things`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 4,
    sort_idx: 22,
    active: 1,
  },
  {
    id: 23,
    title_en: `I am a creative person`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 4,
    sort_idx: 23,
    active: 1,
  },
  {
    id: 24,
    title_en: `I pay attention to details`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 4,
    sort_idx: 24,
    active: 1,
  },
  {
    id: 25,
    title_en: `I like to do filing or typing`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 4,
    sort_idx: 25,
    active: 1,
  },
  {
    id: 26,
    title_en: `I like to analyze things (problems/ situations)`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 4,
    sort_idx: 26,
    active: 1,
  },
  {
    id: 27,
    title_en: `I like to play instruments or sing`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 4,
    sort_idx: 27,
    active: 1,
  },
  {
    id: 28,
    title_en: `I enjoy learning about other cultures`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 4,
    sort_idx: 28,
    active: 1,
  },
  {
    id: 29,
    title_en: `I would like to start my own business`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 5,
    sort_idx: 29,
    active: 1,
  },
  {
    id: 30,
    title_en: `I like to cook`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 5,
    sort_idx: 30,
    active: 1,
  },
  {
    id: 31,
    title_en: `I like acting in plays`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 5,
    sort_idx: 31,
    active: 1,
  },
  {
    id: 32,
    title_en: `I am a practical person`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 5,
    sort_idx: 32,
    active: 1,
  },
  {
    id: 33,
    title_en: `I like working with numbers or charts`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 5,
    sort_idx: 33,
    active: 1,
  },
  {
    id: 34,
    title_en: `I like to get into discussions about issues`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 5,
    sort_idx: 34,
    active: 1,
  },
  {
    id: 35,
    title_en: `I am good at keeping records of my work`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 5,
    sort_idx: 35,
    active: 1,
  },
  {
    id: 36,
    title_en: `I like to lead`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 6,
    sort_idx: 36,
    active: 1,
  },
  {
    id: 37,
    title_en: `I like working outdoors`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 6,
    sort_idx: 37,
    active: 1,
  },
  {
    id: 38,
    title_en: `I would like to work in an office`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 6,
    sort_idx: 38,
    active: 1,
  },
  {
    id: 39,
    title_en: `I'm good at math`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 6,
    sort_idx: 39,
    active: 1,
  },
  {
    id: 40,
    title_en: `I like helping people`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 6,
    sort_idx: 40,
    active: 1,
  },
  {
    id: 41,
    title_en: `I like to draw`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 6,
    sort_idx: 41,
    active: 1,
  },
  {
    id: 42,
    title_en: `I like to give speeches`,
    title_ar: ``,
    test_id: 1,
    chapter_number: 6,
    sort_idx: 42,
    active: 1,
  },
];

const tableName = 'gca_questions';

exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex(tableName).del()
    .then(function () {
      // Inserts seed entries
      return knex(tableName).insert(rows);
    });
};
